metadata:
  displayname: OneDoor Plus
  description: OneDoor plus demo
  homepage: http://septima.dk/search
import:
  sections:
    - name: hearinglist
      dir: $.env.configDir
    - name: guide
      dir: $.env.configDir
    - name: ejerservice
      dir: $.env.configDir
    - name: params
      dir: $.env.configDir
    - name: standardkommune
      dir: $.env.libDir/lib/standardkommune
    #- name: tinglysning
    #  dir: $.env.libDir/lib/standardkommune
    - name: tingbog
      dir: $.env.libDir/lib/standardkommune
    # Indsæt, hvis der ønskes konfliktanalyse mod dmp's katalog
    - name: dmp
      dir: $.env.configDir
    #- name: dmp
    #  dir: $.env.libDir/lib/standardkommune
    # Importér s4 hvis du har brug for at søge i s4 Index
    #- name: s4index
    #  dir: env.libDir/lib/standardkommune
    # Importér og tilpas arcgis hvis du har brug for at søge i arcgis
    #- name: arcgis-eksempel
    #  dir: $env.libDir/lib/standardkommune
controller:
  _type: Septima.Search.Controller
  _options:
    blankBehavior: search
  # De searchers, der skal søges i
  # Udkommentér (#) eller fjern dem du ikke skal bruge
  searchers:
    - _ref: $.searchers.dawa
    - _ref: $.searchers.gsearch
    - _ref: $.searchers.qgis
    - _ref: $.searchers.plansystem
    - _ref: $.searchers.stednavne
    - _ref: $.searchers.cvr
    - _ref: $.searchers.kommunaleproduktionsenhed
    #- _ref: $.searchers.s4Index
    - _ref: $.searchers.poi
    - _ref: $.searchers.ejendomme
    - _ref: $.searchers.bbr
    - _ref: $.searchers.skoledistrikter
    #- _ref: $.searchers.arcgis
    #- _ref: $.tinglysning.geoPartnerSearcher
    - _ref: $.tingbog.searcher
    - _ref: $.searchers.geometrysearcher
    - _ref: $.searchers.geometrysearcher_point
    # Indsæt, hvis der ønskes konfliktanalyse mod dmp's katalog
    - _ref: $.dmp.natur_features
    - _ref: $.dmp.beskyttelse_features
    - _ref: $.dmp.grundvand_features
    - _ref: $.dmp.oevrige_features
    - _ref: $.dmp.map_layers
    - _ref: $.guide.guideSearcher
searchers:
  qgis:
    _type: Septima.Search.OwsUtils.Searcher
    _options:
      url: https://mergin-qgis.k8s-test-127.septima.dk/ows?VERSION=1.1.0&MAP=/data/septima/dmp-lagkatalog/server.qgz
    detailhandlers:
      - _type: Septima.Search.ComposedDetailsHandler
        _options:
          buttonText: Husnumre, Ejendomme
          id: husmat
        detailhandlers:
          - _ref: $.standardkommune.detailhandlers.sqHusnumre
          - _ref: $.standardkommune.detailhandlers.sqEjendomme
          - _ref: $.standardkommune.detailhandlers.sqJordstykker
      - _ref: $.standardkommune.detailhandlers.sqPlaner
      - _ref: $.standardkommune.detailhandlers.sqEjendomme
      - _ref: $.standardkommune.detailhandlers.skraafoto
  kommunaleproduktionsenhed:
    _type: Septima.Search.DataSearcher
    _options:
      iconURI: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2ZXJzaW9uPSIxLjEiIHdpZHRoPSIxNiIgaGVpZ2h0PSIxNiIgdmlld0JveD0iMCAwIDI0IDI0Ij48cGF0aCBkPSJNNCwxOFYyMEg4VjE4SDRNNCwxNFYxNkgxNFYxNEg0TTEwLDE4VjIwSDE0VjE4SDEwTTE2LDE0VjE2SDIwVjE0SDE2TTE2LDE4VjIwSDIwVjE4SDE2TTIsMjJWOEw3LDEyVjhMMTIsMTJWOEwxNywxMkwxOCwySDIxTDIyLDEyVjIySDJaIiBmaWxsPSJjdXJyZW50Q29sb3IiIC8+PC9zdmc+
      source: cvr
      typeId: kommunal_produktionsenhed
      searchableData:
        _type: Septima.Search.SearchableData
        _options:
          cacheTTL: 6000
          singular: kommunal produktionsenhed
          plural: Kommunale p-enheder
          searchProperties:
            - navn
            - adresse
          displaynameProperty: navn
          descriptionProperty: branche
          geometryProperty: geometri
          idProperty: pnummer
          srid: epsg:25832
          data:
            _ref: $.parameters.kommunalePEnheder_url
    detailhandlers:
      - _type: Septima.Search.Details
        _options:
          id: omproduktionsenhed
          asList: false
          details:
            - type: "labelvalue"
              label: "Navn"
              value: "$.navn"
            - type: "labelvalue"
              label: "Branche"
              value: "$.branche"
            - type: link
              linkTitle: Se {$.navn} på virk.dk
              link: https://datacvr.virk.dk/enhed/produktionsenhed/{$.pnummer}
            - type: "labelvalue"
              label: "Tlf"
              value: "$.septima_tlf"
            - type: "result"
              label: "Adresse"
              result:
                searcher:
                  _ref: $.searchers.dawa
                type: adresse
                id: "$.husnummerid"
      - _ref: $.dmp.naturForJordstykke
      - _ref: $.dmp.beskyttelseForJordstykke
      - _ref: $.standardkommune.detailhandlers.skraafoto
  # Her definerer du dine searchere
  skoledistrikter:
    _ref: $.standardkommune.skoledistrikter
  dawa:
    _ref: $.standardkommune.dawa
    detailhandlers:
      - _ref: $.detailhandlers.omHusnummeret
      - _type: Septima.Search.VejInfoProvider
      - _type: Septima.Search.HusnumreForVejProvider
        _options:
          id: husnumre
      - _ref: $.detailhandlers.tilstoedendeEjendomme
      - _ref: $.hearinglist.ejere
      - _ref: $.hearinglist.beboere
      - _ref: $.detailhandlers.cowiGadefoto
      - _ref: $.standardkommune.detailhandlers.skraafoto
      - _ref: $.standardkommune.detailhandlers.bbrInfoOgSager
      # - _ref: $.dmp.naturForJordstykke
      #   _options:
      #     targets: [{source: '*', typeId: 'adresse'}]
      # - _ref: $.dmp.beskyttelseForJordstykke
      #   _options:
      #     targets: [{source: '*', typeId: 'adresse'}]
      # - _ref: $.dmp.grundvandForJordstykke
      #   _options:
      #     targets: [{source: '*', typeId: 'adresse'}]
      - _ref: $.dmp.naturForForGeometry
      - _ref: $.dmp.beskyttelseForGeometry
      - _ref: $.dmp.grundvandForGeometry
      - _ref: $.standardkommune.detailhandlers.sqPlaner
      - _ref: $.standardkommune.detailhandlers.sqKloakoplande
      - _ref: $.standardkommune.detailhandlers.dagiInfo
      - _ref: $.standardkommune.detailhandlers.offentligeLinksForAdresseJordstykke
  plansystem:
    _ref: $.standardkommune.plansystem
    detailhandlers:
      - _ref: $.standardkommune.detailhandlers.planInfo
      - _ref: $.standardkommune.detailhandlers.sqHusnumre
      - _ref: $.standardkommune.detailhandlers.sqEjendomme
      - _ref: $.standardkommune.detailhandlers.sqJordstykker
      - _ref: $.hearinglist.ejere
      - _ref: $.hearinglist.beboere
      - _ref: $.dmp.naturForForGeometry
      - _ref: $.dmp.beskyttelseForGeometry
      #- _ref: $.driftweb.issue_active
      #- _ref: $.hearinglist.virksomheder
      #- _ref: $.standardkommune.detailhandlers.skraafoto
  #s4Index:
  #  _ref: $.s4Index
  #  detailhandlers:
  #    - _type: Septima.Search.S4InfoHandler
  #arcgis:
  # _ref: $.arcgis
  #  detailhandlers:
  #   - _type: Septima.Search.ArcGisFeatureInfoProvider
  cvr:
    _ref: $.standardkommune.cvr
    detailhandlers:
      - _type: Septima.Search.DataApi.CvrInfoProvider
        _options:
          id: cvr
      - _type: Septima.Search.RegnskaberForCvrNummerHandler
      - _ref: $.standardkommune.detailhandlers.skraafoto
      - _ref: $.dmp.naturForJordstykke
      - _ref: $.dmp.beskyttelseForJordstykke
  poi:
    _ref: $.standardkommune.poi
    detailhandlers:
      - _ref: $.standardkommune.detailhandlers.skraafoto
      - _ref: $.standardkommune.detailhandlers.dagiInfo
  ejendomme:
    _ref: $.standardkommune.ejendomme
    detailhandlers:
      - _ref: $.standardkommune.detailhandlers.omEjendommen
      #- _ref: $.standardkommune.detailhandlers.historiskeEjere
      - _ref: $.hearinglist.ejere
      - _ref: $.hearinglist.beboere
      - _type: datafordeler.JordstykkerForEjendom
        _options:
          id: jordstykker
          geosearcher:
            _ref: $.searchers.gsearch
      - _type: Septima.Search.Datafordeler.Bygninger
        _options:
          id: bygning
          searcher:
            _ref: $.searchers.bbr
      - _type: Septima.Search.Datafordeler.VurderingsHandler
        _options:
          id: vurdering
          showVurderingForSamvurdering: true
          showSamvurderedeEjendomme: true
      - _ref: $.standardkommune.detailhandlers.sqPlaner
      - _ref: $.dmp.naturForForGeometry
      - _ref: $.dmp.beskyttelseForGeometry
      # Vælg én tinglysnings-handler
      #- _ref: $.tinglysning.tinglysningerForBfe
      #- _ref: $.tinglysning.tinglysningerForBfe_geopartner
      - _ref: $.tingbog.oplysningerForBfe
      - _ref: $.standardkommune.detailhandlers.dagiInfo
      - _ref: $.standardkommune.detailhandlers.offentligelinksForEjendom
  bbr:
    _ref: $.standardkommune.bbr
    detailhandlers:
      - _ref: $.standardkommune.detailhandlers.bbrInfoOgSager
      - _ref: $.standardkommune.detailhandlers.sqPlaner
      - _type: Septima.Search.SolPotentiale.TagFlader
        _options:
          bbrSearcher:
            _ref: $.searchers.bbr
      - _ref: $.standardkommune.detailhandlers.skraafoto
      - _ref: $.dmp.naturForForGeometry
      - _ref: $.dmp.beskyttelseForGeometry
  stednavne:
    _ref: $.standardkommune.stednavne
    detailhandlers:
      - _type: Septima.Search.InfoForGeoStednavnProvider
        _options:
          id: omstednavn
      - _ref: $.standardkommune.detailhandlers.skraafoto
      - _ref: $.dmp.naturForForGeometry
      - _ref: $.dmp.beskyttelseForGeometry
  gsearch:
    _ref: $.standardkommune.gsearch
    detailhandlers:
      - _ref:  $.detailhandlers.omJordstykket     
      - _ref: $.standardkommune.detailhandlers.bygningerForHusnummerJordstykke
      - _ref: $.standardkommune.detailhandlers.sqPlaner
      - _ref: $.standardkommune.detailhandlers.sqHusnumre
      - _ref: $.hearinglist.ejere
      - _ref: $.hearinglist.beboere
      - _ref: $.dmp.naturForForGeometry
      - _ref: $.dmp.beskyttelseForGeometry
      - _ref: $.dmp.grundvandForGeometry
      - _ref: $.standardkommune.detailhandlers.bbrInfoOgSager
      - _type: Septima.Search.InfoForKommuneProvider
      - _type: Septima.Search.InfoForOpstillingsKredsProvider
      - _type: Septima.Search.InfoForPolitidistriktProvider
      - _type: Septima.Search.InfoForPostdistriktProvider
      - _type: Septima.Search.InfoForRetskredsProvider
      - _type: Septima.Search.InfoForSognProvider
        _options:
          targets: [{source: '*', typeId: 'matrikelnumre'}]
          meta:
            type: labelvalue
            value: Her bruger vi datafordelerens wfs til at finde husnumre indenfor den geografisk inddeling
      - _ref: $.standardkommune.detailhandlers.dagiInfo
        _options:
          targets: [{source: '*', typeId: 'matrikelnumre'}]
      - _ref: $.standardkommune.detailhandlers.offentligeLinksForAdresseJordstykke
      - _ref: $.standardkommune.detailhandlers.skraafoto
        _options:
          targets: [{source: '*', typeId: 'matrikelnumre'}]
  jordstykke_proxy:
    _type: Septima.Search.GeoSearch
    _options:
      targets:
        - matrikelnumre
  geometrysearcher:
    _type: Septima.Search.ClientSearcher
    _options:
      singular: Geometry
      plural: Geometries
      isAsync: false
      usesGeoFunctions: true
      provider:
        _type: Septima.Search.GeometrySearchProvider
    detailhandlers:
      - _ref: $.standardkommune.detailhandlers.sqHusnumre
      - _ref: $.standardkommune.detailhandlers.sqEjendomme
      - _ref: $.standardkommune.detailhandlers.sqJordstykker
      - _ref: $.standardkommune.detailhandlers.sqPlaner
      - _ref: $.dmp.naturForForGeometry
      - _ref: $.dmp.beskyttelseForGeometry
      #- _ref: $.ejerservice.EjerskaberForGeometriProvider
      - _ref: $.hearinglist.ejere
      - _ref: $.hearinglist.beboere
      #- _ref: $.hearinglist.virksomheder
      - _ref: $.standardkommune.detailhandlers.EjdExplorerLinks    
  geometrysearcher_point:
    _type: Septima.Search.ClientSearcher
    _options:
      singular: Point
      plural: Points
      isAsync: false
      usesGeoFunctions: true
      provider:
        _type: Septima.Search.GeometrySearchProvider
    detailhandlers:
      # - _type: Septima.Search.ComposedDetailsHandler
      #   _options:
      #     more: true
      #     buttonText: 'Om punktet'
      #   detailhandlers:
      #     - _ref: $.standardkommune.detailhandlers.sqJordstykker
      #     - _ref: $.standardkommune.detailhandlers.sqEjendomme
      - _ref: $.standardkommune.detailhandlers.sqHusnumre
        _options:
          proxySearcher:
            _ref: $.searchers.jordstykke_proxy
          showProxy: true
      - _ref: $.standardkommune.detailhandlers.sqEjendomme
      - _ref: $.standardkommune.detailhandlers.sqJordstykker
      - _ref: $.standardkommune.detailhandlers.sqPlaner
      - _ref: $.dmp.naturForForGeometry
      - _ref: $.dmp.beskyttelseForGeometry
      - _ref: $.hearinglist.ejere
      - _ref: $.hearinglist.beboere
      - _ref: $.standardkommune.detailhandlers.EjdExplorerLinks    
detailhandlers:
  skraafoto:
    _type: Septima.Search.ComposedDetailsHandler
    _options:
      buttonText: Skråfoto
      id: skraafoto
    detailhandlers:
      - _type: Septima.Search.Details
        _options:
          details: 
            - type: link
              linkTitle: skråfoto.dataforsyningen.dk
              link: https://skraafoto.dataforsyningen.dk/?center={$.geometry.coordinates[0]},{$.geometry.coordinates[1]}
      - _type: Septima.Search.SkraafotoProvider
        _options:
          id: skraafoto
          header: SDFE skråfotos
          token:
            _ref: $.parameters.skraafoto.token   
  omHusnummeret:
    _type: Septima.Search.ComposedDetailsHandler
    _options:
      targets: [{source: '*', typeId: 'adresse'}]
      id: omhusnummer
      more: true
      meta:
        type: labelvalue
        value: Dette er en beskrivelse af hvad denne fane indeholder
      buttonText: 'Om husnummeret'
      buttonImage: 'data:image/svg+xml;base64, PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2ZXJzaW9uPSIxLjEiIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0Ij48cGF0aCBkPSJNNSwxNy41OUwxNS41OSw3SDlWNUgxOVYxNUgxN1Y4LjQxTDYuNDEsMTlMNSwxNy41OVoiIC8+PC9zdmc+'
    detailhandlers:
      - _ref: $.detailhandlers.filarkiv
      - _type: Septima.Search.HusnummerInfoProvider
        _options:
          geosearcher:
            _ref: $.searchers.gsearch
          fields:
            - postadresse
            - antaladdresser
            - matrikelnr
          meta:
            type: labelvalue
            value: Husnummer-info fra Dawa
      - _type: Septima.Search.Datafordeler.EjendomForJordstykkeDawa
        _options:
          id: ejendom
          searcher:
            _ref: $.searchers.ejendomme
          medtagadresser: true
          meta:
            type: labelvalue
            value: Dette er den ejendom, der er registreret på jordstykker. Fra Datafordeleren (ejendomsbeliggenhedsregistret)
      - _ref: $.standardkommune.detailhandlers.bygningerForHusnummerJordstykke
      - _ref: $.standardkommune.detailhandlers.boligerForHusnummer
      - _ref: $.standardkommune.detailhandlers.cvrRegistreringerForHusnummer
      - _ref: $.standardkommune.detailhandlers.sqLokalPlaner
      - _ref: $.standardkommune.detailhandlers.sqKloakoplande
      - _ref: $.standardkommune.detailhandlers.sqSkoledistrikter
      - _type: Septima.Search.HusnummerInfoProvider
        _options:
          geosearcher:
            _ref: $.searchers.gsearch
          buttonText: Koder
          fields:
            - id
            - kode
      - _ref: $.standardkommune.detailhandlers.EjdExplorerLinks

  omVej:
    _type: Septima.Search.ComposedDetailsHandler
    _options:
      targets: [{source: 'Dawa', typeId: 'vej'}]
      id: omvej
      more: true
      meta:
        type: labelvalue
        value: Dette er oplysninger om vejen
      buttonText: 'Om vejen'
    detailhandlers:
      - _type: Septima.Search.Details
        _options:
          asList: false
          details:
            - type: labelvalue
              label: Vejkode
              value: $.properties.kode
            - type: labelvalue
              label: Navn
              value: $.properties.navn
            - type: labelvalue
              label: Adresseringsnavn
              value: $.properties.adresseringsnavn
  tilstoedendeEjendomme:
    _type: s3.SqDetailsHandler
    _options:
      meta:
        type: labelvalue
        value: Dette er tilstødende ejendomme, som overlapper vejens geometri med en buffer på 10 meter
      targets: [{source: 'Dawa', typeId: 'vej'}]
      #proxySearcher:
      #  _ref: $.searchers.jordstykke_proxy
      #showProxy: true
      id: ejendomme_close
     #polygonIntersectsBuffer: 150
      queryGeometryBuffer: 10
      buttonText: Tilstødende ejendomme
      noResultsListItem:
        type: labelvalue
        label: Ejendomme
        value: Ingen ejendomme fundet
    searchers:
      - _ref: $.searchers.ejendomme



  omJordstykket:
    _type: Septima.Search.ComposedDetailsHandler
    _options:
      id: omjordstykke
      more: true
      targets: [{source: '*', typeId: 'matrikelnumre'}]
      buttonText: 'Om jordstykket'
      buttonImage: 'data:image/svg+xml;base64, PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2ZXJzaW9uPSIxLjEiIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0Ij48cGF0aCBkPSJNNSwxNy41OUwxNS41OSw3SDlWNUgxOVYxNUgxN1Y4LjQxTDYuNDEsMTlMNSwxNy41OVoiIC8+PC9zdmc+'
      meta:
        type: labelvalue
        value: Dette er en beskrivelse af hvad denne fane indeholder
    detailhandlers:
      - _ref: $.detailhandlers.filarkiv
      - _type: Septima.Search.JordStykkeInfoProvider
        _options:          
          fields: ["ejendom","adminfo", 'landbrugsnotering', 'arealer', 'sekundaer']         
          ejdSearcher:  
            _ref: $.standardkommune.ejendomme
      - _type: datafordeler.SagsoplysningerForJordstykkeProvider
        _options:
          fetcher:
            _ref: $.standardkommune.datafordelerfetcher
      - _ref: $.standardkommune.detailhandlers.sqLokalPlaner
      - _ref: $.standardkommune.detailhandlers.sqKloakoplande
      - _ref: $.standardkommune.detailhandlers.EjdExplorerLinks
  cowiGadefoto:
    _type: Septima.Search.CowiGadefotoProvider
    _options:
      username: Silkeborg-Kommune
      password: z.GtvDo2.7Qp
      projectname: DDG Silkeborg Kommune
      projectid: 35a025fd-2e8b-4458-b05b-0db8bcb1fbb7

  filarkiv:
    _type: Septima.Search.FilarkivLinkForAdresseMatrikelHandler
    _options:
      kommunenavn: Silkeborg2
      kommunekode: 740
      usePublicSite: false
      showList: false